name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: 
  #     - "development"
  #     - "master"
  #   tags:
  #       - v*
  workflow_dispatch:
    
env:  
  REGISTRY: docker.io # Use docker.io for Docker Hub if empty  
  # IMAGE_NAME: ${{ github.repository }} # github.repository as <account>/<repo>
  IMAGE_NAME: aireset/quepasa # github.repository as <account>/<repo>
  GIT_REF: ${{ github.head_ref || github.ref_name }} # ref_name to get tags/branches
  NODE_ENV: production
  APP_ENV: production
  QUEPASA_CONTAINER_NAME: "quepasa"
  QUEPASA_HOST_NAME: "quepasa"
  QUEPASA_MEMORY_LIMIT: 512M
  QUEPASA_EXTERNAL_PORT: 31000
  QUEPASA_INTERNAL_PORT: 31000
  WEBAPIPORT: 31000
  QUEPASA_BASIC_AUTH_USER: ${{ secrets.DOCKER_USERNAME }}
  QUEPASA_BASIC_AUTH_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # MIGRATIONS: './migrations'
  MIGRATIONS: '/opt/quepasa/migrations'
  WEBSOCKETSSL: false
  DEBUGJSONMESSAGES: false
  HTTPLOGS: false
  
jobs:
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     # list of Docker images to use as base name for tags
      #     images: |
      #       gmorse81/go-rest-api-kubernetes-example
      #     # generate Docker tags based on the following events/attributes
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=semver,pattern={{major}}


      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: set docker tag
        run: |
          echo "DOCKER_TAG=${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
          
      - name: replace docker tag if master
        if: github.ref_name == 'master' || github.ref_name == 'main' 
        run: |
          echo "DOCKER_TAG=${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.0
        with:
          context: "{{defaultContext}}"
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
